//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AquariaToolkit.AquariaWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Aquaria SOAP ServiceBinding", Namespace="urn:aquariasoap")]
    public partial class AquariaSOAPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_angelfish_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_bettafish_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_danio_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_commongoldfish_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_fancygoldfish_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_gourami_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_guppy_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_molly_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_fcm_notcompatible_numberOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_fcm_usuallycompatible_numberOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_fcm_verycompatible_numberOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_massOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_rectangle_volumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_bowfront_volumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_triangleprism_volumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_cornerpentagon_volumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_cylinder_volumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculate_onetime_costOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculate_recurring_costOperationCompleted;
        
        private System.Threading.SendOrPostCallback compare_fish_compatibilityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AquariaSOAPService() {
            this.Url = "http://localhost/aquariasoap/service.php";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_angelfish_idCompletedEventHandler get_angelfish_idCompleted;
        
        /// <remarks/>
        public event get_bettafish_idCompletedEventHandler get_bettafish_idCompleted;
        
        /// <remarks/>
        public event get_danio_idCompletedEventHandler get_danio_idCompleted;
        
        /// <remarks/>
        public event get_commongoldfish_idCompletedEventHandler get_commongoldfish_idCompleted;
        
        /// <remarks/>
        public event get_fancygoldfish_idCompletedEventHandler get_fancygoldfish_idCompleted;
        
        /// <remarks/>
        public event get_gourami_idCompletedEventHandler get_gourami_idCompleted;
        
        /// <remarks/>
        public event get_guppy_idCompletedEventHandler get_guppy_idCompleted;
        
        /// <remarks/>
        public event get_molly_idCompletedEventHandler get_molly_idCompleted;
        
        /// <remarks/>
        public event get_fcm_notcompatible_numberCompletedEventHandler get_fcm_notcompatible_numberCompleted;
        
        /// <remarks/>
        public event get_fcm_usuallycompatible_numberCompletedEventHandler get_fcm_usuallycompatible_numberCompleted;
        
        /// <remarks/>
        public event get_fcm_verycompatible_numberCompletedEventHandler get_fcm_verycompatible_numberCompleted;
        
        /// <remarks/>
        public event get_massCompletedEventHandler get_massCompleted;
        
        /// <remarks/>
        public event get_rectangle_volumeCompletedEventHandler get_rectangle_volumeCompleted;
        
        /// <remarks/>
        public event get_bowfront_volumeCompletedEventHandler get_bowfront_volumeCompleted;
        
        /// <remarks/>
        public event get_triangleprism_volumeCompletedEventHandler get_triangleprism_volumeCompleted;
        
        /// <remarks/>
        public event get_cornerpentagon_volumeCompletedEventHandler get_cornerpentagon_volumeCompleted;
        
        /// <remarks/>
        public event get_cylinder_volumeCompletedEventHandler get_cylinder_volumeCompleted;
        
        /// <remarks/>
        public event calculate_onetime_costCompletedEventHandler calculate_onetime_costCompleted;
        
        /// <remarks/>
        public event calculate_recurring_costCompletedEventHandler calculate_recurring_costCompleted;
        
        /// <remarks/>
        public event compare_fish_compatibilityCompletedEventHandler compare_fish_compatibilityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_angelfish_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_angelfish_id() {
            object[] results = this.Invoke("get_angelfish_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_angelfish_idAsync() {
            this.get_angelfish_idAsync(null);
        }
        
        /// <remarks/>
        public void get_angelfish_idAsync(object userState) {
            if ((this.get_angelfish_idOperationCompleted == null)) {
                this.get_angelfish_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_angelfish_idOperationCompleted);
            }
            this.InvokeAsync("get_angelfish_id", new object[0], this.get_angelfish_idOperationCompleted, userState);
        }
        
        private void Onget_angelfish_idOperationCompleted(object arg) {
            if ((this.get_angelfish_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_angelfish_idCompleted(this, new get_angelfish_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_bettafish_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_bettafish_id() {
            object[] results = this.Invoke("get_bettafish_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_bettafish_idAsync() {
            this.get_bettafish_idAsync(null);
        }
        
        /// <remarks/>
        public void get_bettafish_idAsync(object userState) {
            if ((this.get_bettafish_idOperationCompleted == null)) {
                this.get_bettafish_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_bettafish_idOperationCompleted);
            }
            this.InvokeAsync("get_bettafish_id", new object[0], this.get_bettafish_idOperationCompleted, userState);
        }
        
        private void Onget_bettafish_idOperationCompleted(object arg) {
            if ((this.get_bettafish_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_bettafish_idCompleted(this, new get_bettafish_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_danio_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_danio_id() {
            object[] results = this.Invoke("get_danio_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_danio_idAsync() {
            this.get_danio_idAsync(null);
        }
        
        /// <remarks/>
        public void get_danio_idAsync(object userState) {
            if ((this.get_danio_idOperationCompleted == null)) {
                this.get_danio_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_danio_idOperationCompleted);
            }
            this.InvokeAsync("get_danio_id", new object[0], this.get_danio_idOperationCompleted, userState);
        }
        
        private void Onget_danio_idOperationCompleted(object arg) {
            if ((this.get_danio_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_danio_idCompleted(this, new get_danio_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_commongoldfish_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_commongoldfish_id() {
            object[] results = this.Invoke("get_commongoldfish_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_commongoldfish_idAsync() {
            this.get_commongoldfish_idAsync(null);
        }
        
        /// <remarks/>
        public void get_commongoldfish_idAsync(object userState) {
            if ((this.get_commongoldfish_idOperationCompleted == null)) {
                this.get_commongoldfish_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_commongoldfish_idOperationCompleted);
            }
            this.InvokeAsync("get_commongoldfish_id", new object[0], this.get_commongoldfish_idOperationCompleted, userState);
        }
        
        private void Onget_commongoldfish_idOperationCompleted(object arg) {
            if ((this.get_commongoldfish_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_commongoldfish_idCompleted(this, new get_commongoldfish_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_fancygoldfish_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_fancygoldfish_id() {
            object[] results = this.Invoke("get_fancygoldfish_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_fancygoldfish_idAsync() {
            this.get_fancygoldfish_idAsync(null);
        }
        
        /// <remarks/>
        public void get_fancygoldfish_idAsync(object userState) {
            if ((this.get_fancygoldfish_idOperationCompleted == null)) {
                this.get_fancygoldfish_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_fancygoldfish_idOperationCompleted);
            }
            this.InvokeAsync("get_fancygoldfish_id", new object[0], this.get_fancygoldfish_idOperationCompleted, userState);
        }
        
        private void Onget_fancygoldfish_idOperationCompleted(object arg) {
            if ((this.get_fancygoldfish_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_fancygoldfish_idCompleted(this, new get_fancygoldfish_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_gourami_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_gourami_id() {
            object[] results = this.Invoke("get_gourami_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_gourami_idAsync() {
            this.get_gourami_idAsync(null);
        }
        
        /// <remarks/>
        public void get_gourami_idAsync(object userState) {
            if ((this.get_gourami_idOperationCompleted == null)) {
                this.get_gourami_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_gourami_idOperationCompleted);
            }
            this.InvokeAsync("get_gourami_id", new object[0], this.get_gourami_idOperationCompleted, userState);
        }
        
        private void Onget_gourami_idOperationCompleted(object arg) {
            if ((this.get_gourami_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_gourami_idCompleted(this, new get_gourami_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_guppy_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_guppy_id() {
            object[] results = this.Invoke("get_guppy_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_guppy_idAsync() {
            this.get_guppy_idAsync(null);
        }
        
        /// <remarks/>
        public void get_guppy_idAsync(object userState) {
            if ((this.get_guppy_idOperationCompleted == null)) {
                this.get_guppy_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_guppy_idOperationCompleted);
            }
            this.InvokeAsync("get_guppy_id", new object[0], this.get_guppy_idOperationCompleted, userState);
        }
        
        private void Onget_guppy_idOperationCompleted(object arg) {
            if ((this.get_guppy_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_guppy_idCompleted(this, new get_guppy_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_molly_id", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_molly_id() {
            object[] results = this.Invoke("get_molly_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_molly_idAsync() {
            this.get_molly_idAsync(null);
        }
        
        /// <remarks/>
        public void get_molly_idAsync(object userState) {
            if ((this.get_molly_idOperationCompleted == null)) {
                this.get_molly_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_molly_idOperationCompleted);
            }
            this.InvokeAsync("get_molly_id", new object[0], this.get_molly_idOperationCompleted, userState);
        }
        
        private void Onget_molly_idOperationCompleted(object arg) {
            if ((this.get_molly_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_molly_idCompleted(this, new get_molly_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_fcm_notcompatible_number", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_fcm_notcompatible_number() {
            object[] results = this.Invoke("get_fcm_notcompatible_number", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_fcm_notcompatible_numberAsync() {
            this.get_fcm_notcompatible_numberAsync(null);
        }
        
        /// <remarks/>
        public void get_fcm_notcompatible_numberAsync(object userState) {
            if ((this.get_fcm_notcompatible_numberOperationCompleted == null)) {
                this.get_fcm_notcompatible_numberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_fcm_notcompatible_numberOperationCompleted);
            }
            this.InvokeAsync("get_fcm_notcompatible_number", new object[0], this.get_fcm_notcompatible_numberOperationCompleted, userState);
        }
        
        private void Onget_fcm_notcompatible_numberOperationCompleted(object arg) {
            if ((this.get_fcm_notcompatible_numberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_fcm_notcompatible_numberCompleted(this, new get_fcm_notcompatible_numberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_fcm_usuallycompatible_number", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_fcm_usuallycompatible_number() {
            object[] results = this.Invoke("get_fcm_usuallycompatible_number", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_fcm_usuallycompatible_numberAsync() {
            this.get_fcm_usuallycompatible_numberAsync(null);
        }
        
        /// <remarks/>
        public void get_fcm_usuallycompatible_numberAsync(object userState) {
            if ((this.get_fcm_usuallycompatible_numberOperationCompleted == null)) {
                this.get_fcm_usuallycompatible_numberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_fcm_usuallycompatible_numberOperationCompleted);
            }
            this.InvokeAsync("get_fcm_usuallycompatible_number", new object[0], this.get_fcm_usuallycompatible_numberOperationCompleted, userState);
        }
        
        private void Onget_fcm_usuallycompatible_numberOperationCompleted(object arg) {
            if ((this.get_fcm_usuallycompatible_numberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_fcm_usuallycompatible_numberCompleted(this, new get_fcm_usuallycompatible_numberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_fcm_verycompatible_number", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string get_fcm_verycompatible_number() {
            object[] results = this.Invoke("get_fcm_verycompatible_number", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_fcm_verycompatible_numberAsync() {
            this.get_fcm_verycompatible_numberAsync(null);
        }
        
        /// <remarks/>
        public void get_fcm_verycompatible_numberAsync(object userState) {
            if ((this.get_fcm_verycompatible_numberOperationCompleted == null)) {
                this.get_fcm_verycompatible_numberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_fcm_verycompatible_numberOperationCompleted);
            }
            this.InvokeAsync("get_fcm_verycompatible_number", new object[0], this.get_fcm_verycompatible_numberOperationCompleted, userState);
        }
        
        private void Onget_fcm_verycompatible_numberOperationCompleted(object arg) {
            if ((this.get_fcm_verycompatible_numberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_fcm_verycompatible_numberCompleted(this, new get_fcm_verycompatible_numberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_mass", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double get_mass([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble) {
            object[] results = this.Invoke("get_mass", new object[] {
                        xsddouble});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_massAsync(string xsddouble) {
            this.get_massAsync(xsddouble, null);
        }
        
        /// <remarks/>
        public void get_massAsync(string xsddouble, object userState) {
            if ((this.get_massOperationCompleted == null)) {
                this.get_massOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_massOperationCompleted);
            }
            this.InvokeAsync("get_mass", new object[] {
                        xsddouble}, this.get_massOperationCompleted, userState);
        }
        
        private void Onget_massOperationCompleted(object arg) {
            if ((this.get_massCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_massCompleted(this, new get_massCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_rectangle_volume", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double get_rectangle_volume([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble) {
            object[] results = this.Invoke("get_rectangle_volume", new object[] {
                        xsddouble});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_rectangle_volumeAsync(string xsddouble) {
            this.get_rectangle_volumeAsync(xsddouble, null);
        }
        
        /// <remarks/>
        public void get_rectangle_volumeAsync(string xsddouble, object userState) {
            if ((this.get_rectangle_volumeOperationCompleted == null)) {
                this.get_rectangle_volumeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_rectangle_volumeOperationCompleted);
            }
            this.InvokeAsync("get_rectangle_volume", new object[] {
                        xsddouble}, this.get_rectangle_volumeOperationCompleted, userState);
        }
        
        private void Onget_rectangle_volumeOperationCompleted(object arg) {
            if ((this.get_rectangle_volumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_rectangle_volumeCompleted(this, new get_rectangle_volumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_bowfront_volume", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double get_bowfront_volume([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble) {
            object[] results = this.Invoke("get_bowfront_volume", new object[] {
                        xsddouble});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_bowfront_volumeAsync(string xsddouble) {
            this.get_bowfront_volumeAsync(xsddouble, null);
        }
        
        /// <remarks/>
        public void get_bowfront_volumeAsync(string xsddouble, object userState) {
            if ((this.get_bowfront_volumeOperationCompleted == null)) {
                this.get_bowfront_volumeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_bowfront_volumeOperationCompleted);
            }
            this.InvokeAsync("get_bowfront_volume", new object[] {
                        xsddouble}, this.get_bowfront_volumeOperationCompleted, userState);
        }
        
        private void Onget_bowfront_volumeOperationCompleted(object arg) {
            if ((this.get_bowfront_volumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_bowfront_volumeCompleted(this, new get_bowfront_volumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_triangleprism_volume", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double get_triangleprism_volume([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble) {
            object[] results = this.Invoke("get_triangleprism_volume", new object[] {
                        xsddouble});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_triangleprism_volumeAsync(string xsddouble) {
            this.get_triangleprism_volumeAsync(xsddouble, null);
        }
        
        /// <remarks/>
        public void get_triangleprism_volumeAsync(string xsddouble, object userState) {
            if ((this.get_triangleprism_volumeOperationCompleted == null)) {
                this.get_triangleprism_volumeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_triangleprism_volumeOperationCompleted);
            }
            this.InvokeAsync("get_triangleprism_volume", new object[] {
                        xsddouble}, this.get_triangleprism_volumeOperationCompleted, userState);
        }
        
        private void Onget_triangleprism_volumeOperationCompleted(object arg) {
            if ((this.get_triangleprism_volumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_triangleprism_volumeCompleted(this, new get_triangleprism_volumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_cornerpentagon_volume", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double get_cornerpentagon_volume([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble) {
            object[] results = this.Invoke("get_cornerpentagon_volume", new object[] {
                        xsddouble});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_cornerpentagon_volumeAsync(string xsddouble) {
            this.get_cornerpentagon_volumeAsync(xsddouble, null);
        }
        
        /// <remarks/>
        public void get_cornerpentagon_volumeAsync(string xsddouble, object userState) {
            if ((this.get_cornerpentagon_volumeOperationCompleted == null)) {
                this.get_cornerpentagon_volumeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_cornerpentagon_volumeOperationCompleted);
            }
            this.InvokeAsync("get_cornerpentagon_volume", new object[] {
                        xsddouble}, this.get_cornerpentagon_volumeOperationCompleted, userState);
        }
        
        private void Onget_cornerpentagon_volumeOperationCompleted(object arg) {
            if ((this.get_cornerpentagon_volumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_cornerpentagon_volumeCompleted(this, new get_cornerpentagon_volumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/get_cylinder_volume", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double get_cylinder_volume([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble, [System.Xml.Serialization.SoapElementAttribute("xsd:string")] string xsdstring) {
            object[] results = this.Invoke("get_cylinder_volume", new object[] {
                        xsddouble,
                        xsdstring});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_cylinder_volumeAsync(string xsddouble, string xsdstring) {
            this.get_cylinder_volumeAsync(xsddouble, xsdstring, null);
        }
        
        /// <remarks/>
        public void get_cylinder_volumeAsync(string xsddouble, string xsdstring, object userState) {
            if ((this.get_cylinder_volumeOperationCompleted == null)) {
                this.get_cylinder_volumeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_cylinder_volumeOperationCompleted);
            }
            this.InvokeAsync("get_cylinder_volume", new object[] {
                        xsddouble,
                        xsdstring}, this.get_cylinder_volumeOperationCompleted, userState);
        }
        
        private void Onget_cylinder_volumeOperationCompleted(object arg) {
            if ((this.get_cylinder_volumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_cylinder_volumeCompleted(this, new get_cylinder_volumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/calculate_onetime_cost", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double calculate_onetime_cost([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble, [System.Xml.Serialization.SoapElementAttribute("0", DataType="integer")] string Item0) {
            object[] results = this.Invoke("calculate_onetime_cost", new object[] {
                        xsddouble,
                        Item0});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void calculate_onetime_costAsync(string xsddouble, string Item0) {
            this.calculate_onetime_costAsync(xsddouble, Item0, null);
        }
        
        /// <remarks/>
        public void calculate_onetime_costAsync(string xsddouble, string Item0, object userState) {
            if ((this.calculate_onetime_costOperationCompleted == null)) {
                this.calculate_onetime_costOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncalculate_onetime_costOperationCompleted);
            }
            this.InvokeAsync("calculate_onetime_cost", new object[] {
                        xsddouble,
                        Item0}, this.calculate_onetime_costOperationCompleted, userState);
        }
        
        private void Oncalculate_onetime_costOperationCompleted(object arg) {
            if ((this.calculate_onetime_costCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculate_onetime_costCompleted(this, new calculate_onetime_costCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/calculate_recurring_cost", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public double calculate_recurring_cost([System.Xml.Serialization.SoapElementAttribute("xsd:double")] string xsddouble) {
            object[] results = this.Invoke("calculate_recurring_cost", new object[] {
                        xsddouble});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void calculate_recurring_costAsync(string xsddouble) {
            this.calculate_recurring_costAsync(xsddouble, null);
        }
        
        /// <remarks/>
        public void calculate_recurring_costAsync(string xsddouble, object userState) {
            if ((this.calculate_recurring_costOperationCompleted == null)) {
                this.calculate_recurring_costOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncalculate_recurring_costOperationCompleted);
            }
            this.InvokeAsync("calculate_recurring_cost", new object[] {
                        xsddouble}, this.calculate_recurring_costOperationCompleted, userState);
        }
        
        private void Oncalculate_recurring_costOperationCompleted(object arg) {
            if ((this.calculate_recurring_costCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculate_recurring_costCompleted(this, new calculate_recurring_costCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/aquariasoap/service.php/compare_fish_compatibility", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="integer")]
        public string compare_fish_compatibility([System.Xml.Serialization.SoapElementAttribute("xsd:integer")] string xsdinteger) {
            object[] results = this.Invoke("compare_fish_compatibility", new object[] {
                        xsdinteger});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void compare_fish_compatibilityAsync(string xsdinteger) {
            this.compare_fish_compatibilityAsync(xsdinteger, null);
        }
        
        /// <remarks/>
        public void compare_fish_compatibilityAsync(string xsdinteger, object userState) {
            if ((this.compare_fish_compatibilityOperationCompleted == null)) {
                this.compare_fish_compatibilityOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncompare_fish_compatibilityOperationCompleted);
            }
            this.InvokeAsync("compare_fish_compatibility", new object[] {
                        xsdinteger}, this.compare_fish_compatibilityOperationCompleted, userState);
        }
        
        private void Oncompare_fish_compatibilityOperationCompleted(object arg) {
            if ((this.compare_fish_compatibilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.compare_fish_compatibilityCompleted(this, new compare_fish_compatibilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_angelfish_idCompletedEventHandler(object sender, get_angelfish_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_angelfish_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_angelfish_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_bettafish_idCompletedEventHandler(object sender, get_bettafish_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_bettafish_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_bettafish_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_danio_idCompletedEventHandler(object sender, get_danio_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_danio_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_danio_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_commongoldfish_idCompletedEventHandler(object sender, get_commongoldfish_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_commongoldfish_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_commongoldfish_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_fancygoldfish_idCompletedEventHandler(object sender, get_fancygoldfish_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_fancygoldfish_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_fancygoldfish_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_gourami_idCompletedEventHandler(object sender, get_gourami_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_gourami_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_gourami_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_guppy_idCompletedEventHandler(object sender, get_guppy_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_guppy_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_guppy_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_molly_idCompletedEventHandler(object sender, get_molly_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_molly_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_molly_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_fcm_notcompatible_numberCompletedEventHandler(object sender, get_fcm_notcompatible_numberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_fcm_notcompatible_numberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_fcm_notcompatible_numberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_fcm_usuallycompatible_numberCompletedEventHandler(object sender, get_fcm_usuallycompatible_numberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_fcm_usuallycompatible_numberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_fcm_usuallycompatible_numberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_fcm_verycompatible_numberCompletedEventHandler(object sender, get_fcm_verycompatible_numberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_fcm_verycompatible_numberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_fcm_verycompatible_numberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_massCompletedEventHandler(object sender, get_massCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_massCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_massCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_rectangle_volumeCompletedEventHandler(object sender, get_rectangle_volumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_rectangle_volumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_rectangle_volumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_bowfront_volumeCompletedEventHandler(object sender, get_bowfront_volumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_bowfront_volumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_bowfront_volumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_triangleprism_volumeCompletedEventHandler(object sender, get_triangleprism_volumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_triangleprism_volumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_triangleprism_volumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_cornerpentagon_volumeCompletedEventHandler(object sender, get_cornerpentagon_volumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_cornerpentagon_volumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_cornerpentagon_volumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_cylinder_volumeCompletedEventHandler(object sender, get_cylinder_volumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_cylinder_volumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_cylinder_volumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void calculate_onetime_costCompletedEventHandler(object sender, calculate_onetime_costCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculate_onetime_costCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculate_onetime_costCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void calculate_recurring_costCompletedEventHandler(object sender, calculate_recurring_costCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculate_recurring_costCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculate_recurring_costCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void compare_fish_compatibilityCompletedEventHandler(object sender, compare_fish_compatibilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compare_fish_compatibilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal compare_fish_compatibilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591